services:
  - type: web
    name: page1-contact-form
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MAIL_SENDER
      - key: MAIL_PASSWORD
      - key: MAIL_RECEIVER
      - key: SECRET_KEY
        generateValue: true